# Alembic migration script template

"""Initial database schema

Revision ID: 6cd1533566ec
Revises: 
Create Date: 2026-01-21 19:20:23.175853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cd1533566ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dormitories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dormitories_active', 'dormitories', ['is_active'], unique=False)
    op.create_index('idx_dormitories_city', 'dormitories', ['city'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('platform_origin', sa.String(length=50), nullable=True),
    sa.Column('current_risk_status', sa.Enum('SAFE', 'WATCHLIST', 'RED_FLAG', 'BLACKLISTED', name='riskstatus', native_enum=False), nullable=False),
    sa.Column('risk_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('total_complaints', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_restaurants_name', 'restaurants', ['normalized_name'], unique=False)
    op.create_index('idx_restaurants_platform', 'restaurants', ['platform_origin'], unique=False)
    op.create_index('idx_restaurants_risk', 'restaurants', ['current_risk_status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dorm_id', sa.Integer(), nullable=True),
    sa.Column('tckn_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'DORM_MANAGER', 'SECURITY', 'SYS_ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='chk_email_format'),
    sa.ForeignKeyConstraint(['dorm_id'], ['dormitories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tckn_hash')
    )
    op.create_index('idx_users_dorm', 'users', ['dorm_id'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_tckn_hash', 'users', ['tckn_hash'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('declared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.Enum('SCREENSHOT', 'PHYSICAL_RECEIPT', 'MANUAL_ENTRY', name='entrymethod', native_enum=False), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('manual_note', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('client_ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('gps_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('gps_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_date', 'orders', ['declared_at'], unique=False)
    op.create_index('idx_orders_method', 'orders', ['method'], unique=False)
    op.create_index('idx_orders_receipt_date', 'orders', ['receipt_date'], unique=False)
    op.create_index('idx_orders_restaurant', 'orders', ['restaurant_id'], unique=False)
    op.create_index('idx_orders_user', 'orders', ['user_id'], unique=False)
    op.create_table('health_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('suspected_order_id', sa.UUID(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('symptom_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity_level', sa.Integer(), nullable=True),
    sa.Column('is_verified_by_doctor', sa.Boolean(), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('hospital_name', sa.String(length=255), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INVESTIGATING', 'CONFIRMED', 'DISMISSED', name='reportstatus', native_enum=False), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('resolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('severity_level BETWEEN 1 AND 5', name='chk_severity_range'),
    sa.ForeignKeyConstraint(['suspected_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incidents_date', 'health_incidents', ['report_date'], unique=False)
    op.create_index('idx_incidents_order', 'health_incidents', ['suspected_order_id'], unique=False)
    op.create_index('idx_incidents_status', 'health_incidents', ['status'], unique=False)
    op.create_index('idx_incidents_user', 'health_incidents', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_items_order', 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_order_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_incidents_user', table_name='health_incidents')
    op.drop_index('idx_incidents_status', table_name='health_incidents')
    op.drop_index('idx_incidents_order', table_name='health_incidents')
    op.drop_index('idx_incidents_date', table_name='health_incidents')
    op.drop_table('health_incidents')
    op.drop_index('idx_orders_user', table_name='orders')
    op.drop_index('idx_orders_restaurant', table_name='orders')
    op.drop_index('idx_orders_receipt_date', table_name='orders')
    op.drop_index('idx_orders_method', table_name='orders')
    op.drop_index('idx_orders_date', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_users_tckn_hash', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_dorm', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_restaurants_risk', table_name='restaurants')
    op.drop_index('idx_restaurants_platform', table_name='restaurants')
    op.drop_index('idx_restaurants_name', table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index('idx_dormitories_city', table_name='dormitories')
    op.drop_index('idx_dormitories_active', table_name='dormitories')
    op.drop_table('dormitories')
    # ### end Alembic commands ###
